In [1]:
import numpy as np
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [2]:
type(arr_1d)

numpy.ndarray

In [3]:
arr_1d.ndim

1

In [4]:
arr_2d=np.array([[1,2,3,4],[1,2,3,4]])
print(arr_2d)

[[1 2 3 4]
 [1 2 3 4]]


In [5]:
type(arr_2d)

numpy.ndarray

In [6]:
arr_2d.ndim

2

In [7]:
#size of array
arr_1d.size



4

In [8]:
#shape of array
arr_2d.shape

#(row,coulm)

(2, 4)

In [9]:
#array datatype
arr_1d.dtype

dtype('int32')

In [10]:
arr_2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])