In [2]:
import numpy as np
import random

In [4]:
np.random.random(1)

array([0.83796523])

In [5]:
np.random.random((3,3))

array([[0.53399189, 0.71816719, 0.77094915],
       [0.74532788, 0.02641144, 0.50123077],
       [0.76693193, 0.57713362, 0.03230902]])

In [6]:
np.random.randint(1,4)

3

In [7]:
np.random.randint(1,4,(4,4))

array([[3, 3, 3, 1],
       [3, 2, 2, 3],
       [1, 2, 1, 3],
       [1, 1, 2, 3]])

In [9]:
np.random.randint(1,4,(2,4,4))

array([[[2, 3, 1, 3],
        [2, 2, 1, 3],
        [1, 3, 1, 2],
        [3, 3, 2, 1]],

       [[3, 2, 1, 2],
        [1, 3, 1, 3],
        [3, 3, 1, 2],
        [3, 2, 2, 2]]])

In [10]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [11]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [12]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [13]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [17]:
list = [1,2,3,4]
np.random.choice(list)

2

In [18]:
list = [1,2,3,4]
np.random.choice(list) 
for i in range(20):
    print(np.random.choice(list))

4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3
4
1


In [19]:
list

[1, 2, 3, 4]

In [20]:
np.random.permutation(list)

array([2, 3, 4, 1])