In [11]:
import numpy as np

In [12]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [15]:
mx_1s.dtype

dtype('float64')

In [21]:
 mx_1s=np.ones((4,2))
print(mx_1s)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
mx_1s=np.ones((4,2),dtype=int)
print(mx_1s)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [25]:
mx_0s=np.zeros((4,2),dtype=bool)
print(mx_0s)

[[False False]
 [False False]
 [False False]
 [False False]]


In [26]:
mx_0s=np.zeros((4,2),dtype=str)
print(mx_0s)

[['' '']
 ['' '']
 ['' '']
 ['' '']]


In [28]:
em_str = ''
print(bool(em_str))


False


In [33]:
em_mx=np.empty((5,2))
print(em_mx)

[[nan  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
