In [1]:
#1. 1D Array Slicing
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print("Original array:", a)
print("a[1:4] =", a[1:4])      # Elements from index 1 to 3
print("a[:3] =", a[:3])        # First 3 elements
print("a[2:] =", a[2:])        # From index 2 to end
print("a[-3:-1] =", a[-3:-1])  # Negative indexing
print("a[::2] =", a[::2])      # Step of 2


Original array: [10 20 30 40 50]
a[1:4] = [20 30 40]
a[:3] = [10 20 30]
a[2:] = [30 40 50]
a[-3:-1] = [30 40]
a[::2] = [10 30 50]


In [2]:
#2. 2D Array Slicing
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Original 2D array:\n", b)

print("b[0, 1] =", b[0, 1])        # Element at row 0, col 1
print("b[1, :] =", b[1, :])        # Entire row 1
print("b[:, 2] =", b[:, 2])        # Entire column 2
print("b[0:2, 1:3] =\n", b[0:2, 1:3])  # Slice submatrix


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b[0, 1] = 2
b[1, :] = [4 5 6]
b[:, 2] = [3 6 9]
b[0:2, 1:3] =
 [[2 3]
 [5 6]]


In [3]:
# 3. Slicing with Steps
c = np.array([0, 10, 20, 30, 40, 50])

print("c[::2] =", c[::2])   # Every second element
print("c[::-1] =", c[::-1]) # Reverse array


c[::2] = [ 0 20 40]
c[::-1] = [50 40 30 20 10  0]


In [4]:
#4. Modify Array via Slicing
a = np.array([1, 2, 3, 4, 5])
a[1:4] = 99

print("Modified a:", a)


Modified a: [ 1 99 99 99  5]
