In [7]:
import numpy as np

mx1=np.array([1, 2, 3])         # Create ndarray from list
print(mx1)

mx2=np.zeros((2, 3))           # Create array of zeros
print(mx2)

mx3=np.ones((2, 3))            # Create array of ones
print(mx3)

mx4=np.eye(3)                      # Identity matrix
print(mx4)

mx5=np.full((2, 2), 7)          # Fill with constant
print(mx5)

mx6=np.arange(0, 10, 2)         # Like range() but returns ndarray
print(mx6)

mx7=np.linspace(0, 1, 5)        # 5 evenly spaced values from 0 to 1
print(mx7)

mx8=np.random.rand(2, 3)        # Random values in [0, 1)
print(mx8)

mx9=np.random.randint(1, 10, 5) # 5 random integers from 1 to 9
print(mx9)



[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.67774645 0.76392649 0.57574965]
 [0.5861551  0.86940187 0.58018102]]
[7 7 6 5 6]


In [20]:
a=np.array([1,3,4])
b=np.array([2,4,6])
print(a*b)  #element wise multiplication
print(a+b)  #element wise addition
print(a.dot(b)) #dot production
print(np.add(a,b)) #element wise addition
print(np.multiply(a,b)) #element wise multil

[ 2 12 24]
[ 3  7 10]
38
[ 3  7 10]
[ 2 12 24]


In [23]:
#Numpy Function
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
even_arr = np.arange(1,13,2)
print(even_arr)

[ 1  3  5  7  9 11]


In [27]:
arr_2d =np.linspace(1,10,20)
print(arr_2d)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [31]:
#Reshape 1d array convert to 2d 3d 
arr_2D=arr_1d.reshape(3,4)
print(arr_2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
arr_3D=arr_1d.reshape(2,3,2)
print(arr_3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [33]:
ar=np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [34]:
#ravel() multidimention array convert into 1d
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
#flatten multidimention array convert into 1d
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
#transpose row to clumn conversion
ar.transpose()


array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])